name: Using LambdaTest GH Action

on: push

jobs:
  test-tunnel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Start Tunnel
        uses: LambdaTest/LambdaTest-tunnel-action@v2
        id: tunnel
        with:
          user: ${{ secrets.LT_USERNAME }}
          accessKey: ${{ secrets.LT_ACCESS_KEY }}
          tunnelName: "testTunnel"

      - name: Run Tests
        run: npm test

      - name: Export Tunnel Logs for debugging
        uses: actions/upload-artifact@v2
        with:
          name: tunnel_logs
          path: ${{ steps.tunnel.outputs.logFileName }}

